// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-eQK0cgHmdlvircURITQ4N8uB71hv5M',
    appId: '1:29655497311:web:d8055eb401202b78f3b9ea',
    messagingSenderId: '29655497311',
    projectId: 'pl-forgive-me',
    authDomain: 'pl-forgive-me.firebaseapp.com',
    storageBucket: 'pl-forgive-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdVMp0wtWlKrB9JOI0I3D-G4m15qOrto',
    appId: '1:29655497311:android:c5baee6115bbe33ff3b9ea',
    messagingSenderId: '29655497311',
    projectId: 'pl-forgive-me',
    storageBucket: 'pl-forgive-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVlzjnPnFOpBOfPH3bEw9DNLt-b5vAg0',
    appId: '1:29655497311:ios:d4ddf252bd03311ef3b9ea',
    messagingSenderId: '29655497311',
    projectId: 'pl-forgive-me',
    storageBucket: 'pl-forgive-me.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVlzjnPnFOpBOfPH3bEw9DNLt-b5vAg0',
    appId: '1:29655497311:ios:d4ddf252bd03311ef3b9ea',
    messagingSenderId: '29655497311',
    projectId: 'pl-forgive-me',
    storageBucket: 'pl-forgive-me.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh-eQK0cgHmdlvircURITQ4N8uB71hv5M',
    appId: '1:29655497311:web:2826752e8d90e7fef3b9ea',
    messagingSenderId: '29655497311',
    projectId: 'pl-forgive-me',
    authDomain: 'pl-forgive-me.firebaseapp.com',
    storageBucket: 'pl-forgive-me.firebasestorage.app',
  );

}